### PR TITLE
Ensure datapackage<1.0

### PR DESCRIPTION
**Pull request by roll**
Major v1 release of datapackage is coming. To be sure it will not break this repo.

### CODE REVIEW

**Comment by Stephen-Gates** [comment]
@roll do you know if there plans to update this Extension to support version 1 of the Frictionless Data specification?

**Comment by roll** [comment]
@Stephen-Gates 
I'm not sure. But may be @amercader does know.

**Comment by Stephen-Gates** [comment]
Thanks @roll. Hi @amercader support for version 1 is important for a project I'm working on. Are you able to say with confidence a month this year when this would be done to help me with my planning? If you can't, that's fine and explore some other options. Thanks in advance.

**Comment by amercader** [comment]
Support for v1 is now on master

**Pull request closed without merging**
